import os, sys, shutil
from pathlib import Path
from Utils import FileHelpers

class ZeronSubmodule:
    SUBMODULE_DIR = '.submodule'
    UPDATE_SCRIPT = 'update.py'

    def __init__(self, path = '', relativeToCurrentDir = True):
        if relativeToCurrentDir:
            currentDir = Path(sys.argv[0]).absolute().parent
            self.path = currentDir / path
        else:
            self.path = path

    def extract(self, filter):
        print(f"Updating '{self.path.name}'")
        self.clear()
        FileHelpers.ExtractDirectory(self.path / self.SUBMODULE_DIR, self.path, filter)
        return self

    def clear(self):
        for f in self.path.iterdir():
            pathStr = str(f)
            if self.SUBMODULE_DIR not in pathStr and self.UPDATE_SCRIPT not in pathStr:
                if f.is_dir():
                    shutil.rmtree(f)
                elif f.is_file():
                    f.unlink()
        return self

    def updateCMakeFile(self, appendStr, modifyStrList = []):
        appendStr = f'# START - Generated by Zeron Engine{appendStr}# END - Generated by Zeron Engine\n\n'
        FileHelpers.UpdateFileContent(self.path / 'CMakeLists.txt', appendStr, modifyStrList)
        return self

    def getSubmoduleDir(self):
        return self.path / self.SUBMODULE_DIR